### ISSUE TITLE
Mutating State

### ISSUE THREAD

**Issue by jlag34** [MiguelAZam/jammming#2]
In App.js you do a good job not mutating state in `removeTrack`. Not sure if you proposal choose `filter` because you knew it returned a new array or not. However, in `addTrack` you mutate state when you use `push`. 

```
this.state.playlistTracks.push(track);
```

You should only change state inside of `setState`.  Lastly, this line does nothing:

```
this.setState(this.state.playlistTracks);
```

It seems like it does because you added to the playlist using push but it actually doesn't. Here is an example of the right way to do it:

```
const newList = this.state.playlistTracks.concat(track);
this.setState({ playlistTracks: newList });
```

**Comment by MiguelAZam** [comment]
Thanks Joe, I already make that change in the code. I will take this into account for the final project.
